#!/bin/bash

species=$1
study=$2
sample=$3
nreps=$4
pors=$5
machine=$6

echo "$species $study $sample $nreps $pors $machine"
# Template values are needed for replacement
MERGE_TEMPLATE_LABEL=Pcan-Queen
PE_TEMPLATE_LABEL=Pcan-21Q
SE_TEMPLATE_LABEL=Amel-afbCTRL

# make the genome dir
mkdir -p ${species}/genome

# only copy GFF parse makefile if it doesn't exist
if [ ! -f "${species}/genome/Makefile" ]; then
  cp  ../makefiles/Makefile_parse_GFF3_template ${species}/genome/Makefile
  sed -i -e "s/Pcan/${species}/g;" ${species}/genome/Makefile
fi

# check for sample dir
if [ -d ${species}/${study}/${sample} ]; then
  echo 'This sample already exists.'
  exit 1
fi

mkdir -p ${species}/${study}/${sample}

if (( "$nreps" == 1 )); then
  pushd ${species}/${study}/${sample}
  ln -s  ../../genome
  popd
  if [ $pors == "p" ]; then
    cp ../makefiles/${machine}Makefile_pe_template ${species}/${study}/${sample}/Makefile
    # replace with proper sample name
    sed -i -e "s/${PE_TEMPLATE_LABEL}/${sample}/;" ${species}/${study}/${sample}/Makefile
  else
    cp ../makefiles/${machine}Makefile_se_template ${species}/${study}/${sample}/Makefile
    # replace with proper sample name
    sed -i -e "s/${SE_TEMPLATE_LABEL}/${sample}/;" ${species}/${study}/${sample}/Makefile
  fi
else # ... there are multiple replicates
  # copy merge makefile if there are more than one replicates
  cp ../makefiles/${machine}Makefile_merge_template ${species}/${study}/${sample}/Makefile
  # replace with proper sample name
  sed -i -e "s/${MERGE_TEMPLATE_LABEL}/${sample}/;" ${species}/${study}/${sample}/Makefile

  for ((i=1; i<= $nreps; i++)); do
    replicate_path=${species}/${study}/${sample}/replicate$i
    echo ${replicate_path}
    mkdir -p ${replicate_path}
    # link the genome to the replicate
    pushd ${replicate_path}
    ln -s  ../../../genome
    popd
  
    if [ $pors == "p" ]; then
      cp ../makefiles/${machine}Makefile_pe_template ${replicate_path}/Makefile
      # replace with proper sample name
      sed -i -e "s/${PE_TEMPLATE_LABEL}/${sample}${i}/;" ${replicate_path}/Makefile
    else
      cp ../makefiles/${machine}Makefile_se_template ${replicate_path}/Makefile
      # replace with proper sample name
      sed -i -e "s/${SE_TEMPLATE_LABEL}/${sample}${i}/;" ${replicate_path}/Makefile
    fi
  done
fi
